# Generated by Django 5.2.6 on 2025-09-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='expires_date',
            new_name='expiry_date',
        ),
    ]
